name:                privacy
version:             0.1.0.5
github:              "oisdk/privacy"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/oisdk/privacy#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
    - -fwarn-redundant-constraints
    - -Wcompat

tests:
  privacy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - privacy
    - smallcheck
    - tasty
    - tasty-smallcheck
  privacy-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - privacy
    - doctest
    - QuickCheck
