name:                privacy
version:             0.1.0.10
github:              "oisdk/privacy"
license:             MIT
author:              "Donnacha Oisín Kidney"
maintainer:          "mail@doisinkidney.com"
copyright:           "2018 Donnacha Oisín Kidney"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/oisdk/privacy#readme>

dependencies:
- base >= 4.7 && < 5
- semigroupoids
- containers
- static-canvas >= 0.2.0.3
- diagrams >= 1.4
- diagrams-cairo >= 1.4
- diagrams-lib >= 1.4.2
- magic >= 1.1
- diagrams-contrib >= 1.4.2.1
- diagrams-core >= 1.4.0.1
- diagrams-solve >= 0.1.1
- diagrams-svg >= 1.4.1.1
- dual-tree >= 0.2.1
- cubicbezier >= 0.6.0.5
- mfsolve >= 0.3.2.0
- fast-math >= 1.0.2
- statistics >= 0.14.0.2
- ihaskell
- ihaskell-charts
- ihaskell-aeson
- ihaskell-blaze
- ihaskell-charts
- ihaskell-diagrams
- ihaskell-gnuplot
- ihaskell-hatex
- ihaskell-juicypixels
- ihaskell-magic
- ihaskell-plot
- Chart
- colour
- data-default-class
- lens
- profunctors

library:
  source-dirs: src

ghc-options:
- -Wall
- -fwarn-incomplete-record-updates
- -fwarn-incomplete-uni-patterns
when:
  - condition: impl(ghc >= 8.0)
    ghc-options:
    - -fwarn-redundant-constraints
    - -Wcompat

tests:
  privacy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - privacy
    - smallcheck
    - tasty
    - tasty-smallcheck
  privacy-doctests:
    main:                doctests.hs
    source-dirs:         doctest
    ghc-options:
    - -threaded
    dependencies:
    - privacy
    - doctest
    - QuickCheck
